version: '3'

services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - '3307:3307'
    environment:
       MYSQL_DATABASE: 'laysifDB'
       MYSQL_USER: 'admin'
       MYSQL_PASSWORD: 'command123'
       MYSQL_ROOT_PASSWORD: 'command123'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app_dir
    ports:
      - "8000:8000"
    depends_on:
      - db