# Generated by Django 3.2 on 2021-12-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_alter_meetup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
