# Generated by Django 3.2 on 2022-01-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_alter_meetup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
